name: Deploy FastAPI Application

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run FastAPI application
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          uvicorn app:app --host 0.0.0.0 --port 8000
